FROM maven:3.8.4-openjdk-17 as builder
WORKDIR /app
COPY ../../bot/RussianGeographicalSociety /app/.
RUN mvn -f /app/pom.xml clean package -Dmaven.test.skip=true

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/bot.jar /app/bot.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/bot.jar"]