package com.shulmin.pavel.russiangeographicalsociety.constant;

public enum BotStates {
    START,
    NAME_RECEIVED,
    AGE_RECEIVED,
    SEX_RECEIVED,
    PLACE_BORN_RECEIVED,
    PLACE_LIVE_RECEIVED,
    SOCIAL_RECEIVED,
    TYPE_RECEIVED,
    CATEGORY_RECEIVED,
    FIRST_GENERAL_ANSWER_RECEIVED,
    SECOND_GENERAL_ANSWER_RECEIVED,
    THIRD_GENERAL_ANSWER_RECEIVED,
    FIRST_ANSWER_RECEIVED,
    SECOND_ANSWER_RECEIVED,
    THIRD_ANSWER_RECEIVED,
    PHOTOS_RECEIVED,
    FINAL
}
