version: 0.0.1

services:

  bot:
    image: bot:0.0.1
    container_name: bot
    build:
      context: ../../
      dockerfile: ./bot/RussianGeographicalSociety/Dockerfile.core
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/rgs_ambassadors

  backend:
    image: backend:0.0.1
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.core
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/rgs_ambassadors

  postgres:
    image: postgres:14.4-alpine
    container_name: postgreSQL
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: rgs_ambassadors
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: ["postgres", "-c", "log_statement=all"]